export type Category = {
  id: string;
  kind: "job" | "service";
  name: string;
  icon: string;
};
export type Catalog = {
  categories: Category[];
  roles: { id: string; categoryId: string; name: string }[];
  locations: {
    id: string;
    area: string;
    latitude: number;
    longitude: number;
  }[];
};
export type Job = {
  id: string;
  ownerId: string;
  categoryId?: string;
  categoryName?: string;
  categoryIcon?: string;
  roleId?: string;
  roleName?: string;
  roleIcon?: string;
  title: string;
  customTitle?: string;
  area: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  startsAt: number;
  duration?: string;
  endsAt?: number | null;
  hours?: string;
  startTime?: string;
  endTime?: string;
  workers: number;
  experience?: string;
  payPaise: number;
  payUnit: string;
  paidWhen?: string;
  extras?: string[];
  details: string;
  status: string;
  ownerName: string;
  ownerPhone?: string;
  ownerPhotoUrl?: string;
  applicantCount?: number;
  applicants?: {
    id: string;
    name: string;
    phone?: string;
    area?: string;
    photoUrl?: string;
    appliedAt?: number;
    status?: string;
  }[];
  distanceKm?: number;
  createdAt?: number;
};
export type Professional = {
  userId: string;
  id: string;
  title: string;
  category: string;
  area: string;
  distanceKm: number;
  experience: number;
  rating: number | null;
  completed: number;
};
export type Connection = {
  id: string;
  kind: "job" | "service";
  status: string;
  title: string;
  otherName: string;
  ownerId: string;
  workerId: string;
  ownerConfirmedAt: number | null;
  workerConfirmedAt: number | null;
  reviewed: number;
};
