ALTER TABLE interactions ADD COLUMN area TEXT;
ALTER TABLE interactions ADD COLUMN latitude REAL;
ALTER TABLE interactions ADD COLUMN longitude REAL;
ALTER TABLE interactions ADD COLUMN scheduled_at INTEGER;
CREATE TRIGGER request_location BEFORE INSERT ON interactions WHEN NEW.kind='service' BEGIN
 SELECT CASE WHEN NEW.area IS NULL OR NEW.latitude IS NULL OR NEW.longitude IS NULL OR NEW.scheduled_at IS NULL OR NEW.latitude NOT BETWEEN -90 AND 90 OR NEW.longitude NOT BETWEEN -180 AND 180 THEN RAISE(ABORT,'REQUEST_LOCATION_REQUIRED') END;
END;
