-- Add Post Work v2 columns to jobs table
ALTER TABLE jobs ADD COLUMN address TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN duration TEXT NOT NULL DEFAULT 'one';
ALTER TABLE jobs ADD COLUMN hours TEXT NOT NULL DEFAULT 'full';
ALTER TABLE jobs ADD COLUMN start_time TEXT NOT NULL DEFAULT '09:00';
ALTER TABLE jobs ADD COLUMN end_time TEXT NOT NULL DEFAULT '17:00';
ALTER TABLE jobs ADD COLUMN paid_when TEXT NOT NULL DEFAULT 'after';
ALTER TABLE jobs ADD COLUMN extras TEXT NOT NULL DEFAULT '[]';
